# Generated by Django 5.0.4 on 2024-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('disc', models.TextField(max_length=500)),
                ('publish_date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
